spring:
   application:
      name: apigateway
   cloud:
      loadbalancer:
         retry:
            enabled: true
      
---

spring:
  profiles: 
    include:
      - local
      - zuul
      - service
      - hystrix
      - ribbon
      - eureka

server:
  port: 8762
  
  
header:
   authorization: Authorization

jwt:
   apikey: jwtapikey
   login:
      memberKey: memberId
      valid:
         minute: 60
   access:
      valid:
         minute: 1
   refresh:
      valid:
         day: 30 
   
   
---

spring:
  profiles: 
    include:
      - dev
      - zuul
      - service
      - hystrix
      - ribbon
      - eureka

server:
  port: 8762 
  
---

spring:
  profiles: 
    include:
      - prd
      - zuul
      - service
      - hystrix
      - ribbon
      - eureka

server:
  port: 8762

aws:
  ec2:
    serviceIp:
      first: 999.99.99
      second: 888.88.88
